### ISSUE TITLE
Quality Report Check: Funding Organization

### ISSUE THREAD

**Issue by emilyarobles** [NCEAS/metadig-checks#428] opened 2021-11-15 23:26 UTC
## Description

Check if an award funder has been specified from a controlled list.

## Priority

- FAIR: Optional

## Issues
- ESS-DIVE will need to provide a list of approved awards/funders to check against in CSV format

## Procedure

Check that the award funder provided is present in a periodically updated list of approved organizations. 

## Response for Failed Check
Warning. The funding organization listed is not from the controlled list.

**Comment by gothub** [comment] 2021-11-16 18:55
@emilyarobles is this the same as https://github.com/NCEAS/metadig-checks/issues/421?

**Comment by emilyarobles** [comment] 2021-11-17 03:35
@gothub Yes, this is a duplicate - sorry about that. I am not able to edit issues that are not my own so I cannot add checks into the table in issue [#423](https://github.com/NCEAS/metadig-checks/issues/423) and I also am not able to add labels to the issues I create. I sent an email about this that includes a bit more detail - I think it could be a permissions issue?

**Comment by gothub** [comment] 2021-12-07 19:57
Duplicate of https://github.com/NCEAS/metadig-checks/issues/421

**Closed by gothub** 2021-12-07 19:57 UTC
Labels: ESS-DIVE Suite
