### ISSUE TITLE
resource.distribution.contact.identifier.present

### ISSUE THREAD

**Issue by tedhabermann** [NCEAS/metadig-checks#184] opened 2019-12-18 19:58 UTC
## Description
Checking the existence of a resource.distribution.contact.identifier
## Priority
Optional
## Issues
None
## Procedure
Determine whether a resource.distribution.contact.identifier is present

**Comment by gothub** [comment] 2020-04-08 20:36
Duplicate of #55

**Closed by gothub** 2020-04-08 20:36 UTC
Labels: Accessible, DataCite, FAIR Suite, Reusable, Supporting
